# Access the id_github file from Secret Manager, and setup SSH
steps:
- name: 'gcr.io/cloud-builders/git'
  secretEnv: ['SSH_KEY']
  entrypoint: 'bash'
  args:
  - -c
  - |
    #echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    echo "$$SSH_KEY" >> /root/.ssh/id_rsa
    #chmod 400 /root/.ssh/id_rsa
    chmod 400 /root/.ssh/id_rsa
    #ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    #echo ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
    #cp known_hosts.github /home/anil_gochipathala/.ssh/known_hosts
  volumes:
  - name: 'ssh'
    path: /root/.ssh

# Clone the  repository
- name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --recurse-submodules
  - git@github.com:Basis1977/gak.git
  volumes:
  - name: 'ssh'
    path: /root/.ssh

availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_ID/secrets/ass-hole/versions/latest
    env: 'SSH_KEY'